name: Build, Push and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Dockerfile exists
        run: ls -la ./

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: volkyodha/dock_clientes:latest

  run-container:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker container
        run: |
          docker pull volkyodha/dock_clientes:latest
          docker run -d -p 3001:3001 volkyodha/dock_clientes:latest

      - name: Post build
        run: echo "Docker image build, push, and run completed."
